
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Apr 02 18:17:07 MDT 2013
//----------------------------------------------------

import AST.*;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSEBRACE = 24;
  public static final int AND = 14;
  public static final int LT = 8;
  public static final int NE = 12;
  public static final int ELSE = 19;
  public static final int OPENBRACE = 23;
  public static final int PLUS = 2;
  public static final int INT = 22;
  public static final int OR = 15;
  public static final int LP = 25;
  public static final int SEMI = 27;
  public static final int WHILE = 20;
  public static final int RP = 26;
  public static final int SLASH = 5;
  public static final int NOT = 13;
  public static final int RETURN = 17;
  public static final int TRUE = 31;
  public static final int IF = 18;
  public static final int GT = 7;
  public static final int ID = 29;
  public static final int LE = 9;
  public static final int BOOLEAN = 21;
  public static final int STRING = 30;
  public static final int COMMA = 28;
  public static final int NUMBER = 34;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int BREAK = 16;
  public static final int FALSE = 32;
  public static final int GE = 10;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int VOID = 33;
  public static final int PER = 6;
}

